version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: despliegue-api-rest
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: despliegue-api-rest

      # Configuración de la base de datos (Neon)
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-twilight-waterfall-adh2pm4g-pooler.c-2.us-east-1.aws.neon.tech/pets?sslmode=require&channelBinding=require
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_ciR1In8OvFYW
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # Configuración JPA / Hibernate
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: "true"
    restart: unless-stopped
